# Generated by Django 5.1.1 on 2024-11-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profiles',
        ),
    ]
