# Generated by Django 5.1.1 on 2024-11-26 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genre',
            table='genres',
        ),
        migrations.AlterModelTable(
            name='movie',
            table='movies',
        ),
        migrations.AlterModelTable(
            name='searchterm',
            table='search_terms',
        ),
    ]
